http://localhost:8000/api/user
content-type: application/json
Authorization: Bearer 1234567890aa
Accept: application/json

###
http://localhost:8000/api/user
content-type: application/json
Authorization: Bearer 1234567890bb
Accept: application/json
