openapi: 3.0.2
info:
  description: |-
    Miyameshi の API 仕様書
  version: "1.0.0"
  title: "Miyameshi"
servers:
  - url: http://localhost:8000/api/admin
tags:
  - name: "selection-post"
    description: "ブログ関連API"
  - name: "shop"
    description: "店舗管理API"

paths:
  /selection-post:
    get:
      tags:
        - selection-post
      summary: ブログ一覧取得API
      description: ブログ一覧を取得する
      parameters:
        - name: limit
          in: query
          description: 取得数
          schema:
            type: integer
            default: 10
        - name: releases
          in: query
          description: 公開設定
          schema:
            type: array
            items:
              type: "boolean"
        - name: id
          in: query
          description: SelectionPostのID
          schema:
            type: integer
        - name: created_at
          in: query
          description: 作成日時 (paginationで使用)
          schema:
            type: string
        - name: updated_at
          in: query
          description: 更新日時 (paginationで使用)
          schema:
            type: string
        - name: content-type
          in: header
          schema:
            type: string
            default: application/json
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags:
        - selection-post
      summary: 新規ブログ追加API
      description: ブログを追加する
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
            default: application/json
      requestBody:
        required: true
        description: The selection-post to create.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelectionPostObject'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /selection-post/{selectionPostId}:
    get:
      tags:
        - selection-post
      summary: ブログの個別情報取得API
      description: |-
        idはSelectionPostテーブルのID。
      parameters:
        - name: selectionPostId
          in: path
          schema:
            type: integer
          required: true
        - name: content-type
          in: header
          schema:
            type: string
            default: application/json
        - name: Accept
          in: header
          schema:
            type: string
            default: application/json
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - selection-post
      summary: ブログの更新API
      description: |-
        idはSelectionPostテーブルのID。
      parameters:
        - name: selectionPostId
          in: path
          schema:
            type: integer
          required: true
        - name: Accept
          in: header
          schema:
            type: string
            default: application/json
      requestBody:
        required: true
        description: The selection-post to create.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelectionPostObject'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - selection-post
      summary: ブログの削除取得API
      description: |-
        idはSelectionPostテーブルのID。
      parameters:
        - name: selectionPostId
          in: path
          schema:
            type: integer
          required: true
        - name: Accept
          in: header
          schema:
            type: string
            default: application/json
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /shop:
    get:
      tags:
        - shop
      summary: 店舗一覧取得API
      description: 店舗一覧を取得する
      parameters:
        - name: limit
          in: query
          description: 取得数
          schema:
            type: integer
            default: 10
        - name: releases
          in: query
          description: 公開設定
          schema:
            type: array
            items:
              type: "boolean"
        - name: id
          in: query
          description: ShopのID
          schema:
            type: integer
        - name: created_at
          in: query
          description: 作成日時 (paginationで使用)
          schema:
            type: string
        - name: updated_at
          in: query
          description: 更新日時 (paginationで使用)
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags:
        - shop
      summary: 新規店舗追加API
      description: 店舗を追加する
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
            default: application/json
      requestBody:
        required: true
        description: The shop to create.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShopObject'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /shop/{shopId}:
    get:
      tags:
        - shop
      summary: 店舗の個別情報取得API
      description: |-
        idはShopテーブルのID。
      parameters:
        - name: shopId
          in: path
          schema:
            type: integer
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - shop
      summary: ブログの更新API
      description: |-
        idはShopテーブルのID。
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
            default: application/json
        - name: shopId
          in: path
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        description: The shop to create.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShopObject'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - shop
      summary: ブログの削除取得API
      description: |-
        idはShopテーブルのID。
      parameters:
        - name: shopId
          in: path
          schema:
            type: integer
          required: true
        - name: Accept
          in: header
          schema:
            type: string
            default: application/json
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


components:
  schemas:
    SelectionPostObject:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        contents:
          type: string
        image:
          type: string
          format: url
        release:
          type: boolean
          default: false
        firebase_area_ids:
          type: array
          items:
            type: "string"
        firebase_shop_ids:
          type: array
          items:
            type: "string"
      required:
        - title
    ShopObject:
      type: object
      properties:
        name:
          type: string
          default: 'かっこいい店'
        nameKana:
          type: string
          default: 'かっこいいみせ'
        prefixName:
          type: string
          default: '居酒屋'
        description:
          type: string
          default: '宇都宮1の居酒屋です'
        intro:
          type: string
          default: '宇都宮1の居酒屋です'
        priority:
          type: number
          default: 1
        release:
          type: boolean
          default: true
        publishFrom:
          type: string
          format: date
          default: null
        publishTo:
          type: string
          format: date
          default: null
        displayMode:
          type: string
          default: 'NORMAL'
        imageLink:
          type: string
          nullable: true
          default: 'https://example.com'
        subImageLink:
          type: array
          nullable: true
          default: ['https://example.com']
          items:
            type: string
        menuImageLink:
          type: array
          nullable: true
          default: ['https://example.com']
          items:
            type: string
        appearanceImageLink:
          type: array
          nullable: true
          default: ['https://example.com']
          items:
            type: string
        tel:
          type: string
          nullable: true
          default: 000-0000-0000
        postal:
          type: string
          nullable: true
          default: 321-0000
        address:
          type: string
          nullable: true
          default: '栃木県宇都宮市旭'
        buildingName:
          type: string
          nullable: true
          default: 'アパート名'
        locationLatitude:
          type: number
          nullable: true
          format: float
          default: 0
        locationLongitude:
          type: number
          nullable: true
          format: float
          default: 0
        facebookLink:
          type: string
          nullable: true
          format: uri
          default: 'https://example.com'
        instaLink:
          type: string
          nullable: true
          format: uri
          default: 'https://example.com'
        homepageLink:
          type: string
          nullable: true
          format: uri
          default: 'https://example.com'
        twitterLink:
          type: string
          nullable: true
          format: uri
          default: 'https://example.com'
        lineLink:
          type: string
          nullable: true
          format: uri
          default: 'https://example.com'
        youtubeLink:
          type: string
          nullable: true
          format: uri
          default: 'https://example.com'
        ubereatsLink:
          type: string
          nullable: true
          format: uri
          default: 'https://example.com'
        gotoeatLink:
          type: string
          nullable: true
          format: uri
          default: 'https://example.com'
        priceRange:
          type: string
          nullable: true
          default: 'UNDER_500'
          enum:
            - 'UNDER_500'
            - 'BETWEEN_500_AND_1000'
            - 'BETWEEN_1000_AND_2000'
            - 'BETWEEN_2000_AND_3000'
            - 'BETWEEN_3000_AND_5000'
            - 'BETWEEN_5000_AND_10000'
            - 'OVER_10000'
        businessStartHour1:
          type: string
          nullable: true
          default: '18:00:00'
        businessEndHour1:
          type: string
          nullable: true
          default: '18:00:00'
        businessLoHour1:
          type: string
          nullable: true
          default: '18:00:00'
        businessStartHour2:
          type: string
          nullable: true
          default: '18:00:00'
        businessEndHour2:
          type: string
          nullable: true
          default: '18:00:00'
        businessLoHour2:
          type: string
          nullable: true
          default: '18:00:00'
        businessStartHour3:
          type: string
          nullable: true
          default: '18:00:00'
        businessEndHour3:
          type: string
          nullable: true
          default: '18:00:00'
        businessLoHour3:
          type: string
          nullable: true
          default: '18:00:00'
        parkingLot:
          type: string
          nullable: true
          default: '4つあります'
        seat:
          type: string
          nullable: true
          default: '40席'
        access:
          type: string
          nullable: true
          default: '宇都宮駅から徒歩5分'
        regularHoliday:
          type: string
          nullable: true
          default: '年末年始・祝日'
        reservervationMaxNumber:
          type: number
          nullable: true
          default: 4
        creditCard:
          type: string
          nullable: true
          default: '未対応'
        electronicMoney:
          type: string
          nullable: true
          default: '未対応'
        aboutSmoking:
          type: string
          nullable: true
          default: '未対応'
        totalNumberOfSeats:
          type: string
          nullable: true
          default: '未対応'
        privateRoom:
          type: string
          nullable: true
          default: '未対応'
        canTakeout:
          type: boolean
          default: false
        canGotoeat:
          type: boolean
          default: false
        canReservation:
          type: boolean
          default: false
        periodOfTime:
          type: array
          nullable: true
          default: ['LUNCH']
          items:
            type: string
            enum:
              - 'MORNING'
              - 'LUNCH'
              - 'NIGHT'
              - 'ALL_TIME'
        instaNumber:
          type: number
          nullable: true
          default: 0
        instaShopLink:
          type: string
          nullable: true
          format: uri
          default: 'https://example.com'
        instaIframe:
          type: string
          nullable: true
          default: '<iframe></iframe>'
        firebaseShopId:
          type: string
          nullable: true
          default: 'aaa'
        firebaseKeywordIds:
          type: array
          nullable: true
          default: ['aaa']
          items:
            type: string
        firebaseDishIds:
          type: array
          nullable: true
          default: ['aaa']
          items:
            type: string
      required:
        - name
        - displayMode
    SuccessResponse:
      type: object
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          description: ステータスコード
        message:
          type: string
          description: エラーメッセージ
      required:
        - code
        - message
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Credentials or access token for API

security:
  - Bearer: []
